---
title: "Semantic_snakes"
output: html_document
date: "2023-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# load packages
```{r}
library(tidyverse)
library(dplyr)
library(lme4)
```

```{r}
descriptive = read.csv("sona11.28(updated).csv")%>%
  mutate(rt=as.numeric(rt), revised_correct=as.numeric(revised_correct))
```
# attention trials data frame
```{r}
attention_trials = descriptive %>%
  filter(typeoftrial == "attention")%>%
  select(ID, revised_response, novel1, novel2, novel3, revised_correct)

#mean
attention_trials %>% 
  summarize(mean_accuracy = mean(revised_correct),
            sd_accuracy = sd(revised_correct))

#summarize participant accuracy
subject_attention_accuracy = attention_trials %>%
  group_by(ID) %>%
  summarize(mean_accuracy = mean(revised_correct))
# identify low accuracy IDs

low_acc_IDs = subject_attention_accuracy%>% 
  filter(mean_accuracy < 0.75) %>%
  pull(ID)
```
#association

```{r}
scoring = read_csv("association_scoring.csv")%>%
  arrange(cue, response)
association_trials = descriptive %>%
  filter(typeoftrial == "association") %>%
  select (ID, revised_response, cue) %>%
  rename(response = "revised_response") %>%
  mutate(response = tolower(response)) %>%
  left_join(scoring)

# congruence trials

congruence_trials = association_trials %>%
  filter(!is.na(congruence)) %>%
  filter(congruence %in% c("congruent", "incongruent")) %>%
  filter(type_of_association %in% c("direct", "shared"))

congruence_counts = congruence_trials %>%
  group_by(ID, cue_type, congruence, type_of_association) %>%
  count() %>%
  group_by(ID, cue_type) %>%
  mutate(proportion = n / sum(n))

congruence_counts %>%
  filter(congruence == "congruent") %>%
  ungroup() %>%
  summarise(mean_prop = mean(proportion))

wide_counts = congruence_counts %>%
  select(ID, cue_type, congruence, type_of_association, proportion) %>%
  pivot_wider(names_from = congruence, values_from = proportion)%>%
  mutate(incongruent = ifelse(is.na(incongruent), 0, incongruent),
       congruent = ifelse(is.na(congruent), 0, congruent)) %>%
  mutate(prop = congruent - incongruent)

mean(wide_counts$prop)

### counts by type of association 

association_type_occurrence = wide_counts %>%
  select(ID, cue_type, type_of_association, prop)%>%
  pivot_wider(names_from = type_of_association, values_from = prop)%>%
  mutate(shared = ifelse(is.na(shared), 0, shared),
         direct = ifelse(is.na(direct), 0, direct))

mean(association_type_occurrence$direct)
mean(association_type_occurrence$shared)

```

#IAT accuracy by participant
```{r}
subset_data <- descriptive %>%
  filter(typeoftrial %in% c("congruent_iat", "incongruent_iat")) %>%
  mutate(correct_numeric = ifelse(correct, 1, 0))

subject_accuracy_iat <- subset_data %>%
  group_by(ID) %>%
  summarise(mean_accuracy = mean(correct_numeric)) %>%
  ungroup() %>%
  select(ID, mean_accuracy)

# Mean accuracy for 'congruent_iat' trials
congruent_accuracy <- subset_data %>%
  filter(typeoftrial == "congruent_iat") %>%
  group_by(ID) %>%
  summarise(mean_accuracy_congruent = mean(correct_numeric)) %>%
  ungroup()

# Mean accuracy for 'incongruent_iat' trials
incongruent_accuracy <- subset_data %>%
  filter(typeoftrial == "incongruent_iat") %>%
  group_by(ID) %>%
  summarise(mean_accuracy_incongruent = mean(correct_numeric)) %>%
  ungroup()

# Merge 
subject_accuracy_iat <- left_join(subject_accuracy_iat, congruent_accuracy, by = "ID")
subject_accuracy_iat <- left_join(subject_accuracy_iat, incongruent_accuracy, by = "ID")
```


# iat congruent by novel word
```{r}
iat_congruent_trials = descriptive %>%
  filter(typeoftrial == "congruent_iat", cue %in% c("dodish", "foobly", "geck", "mipp"))%>%
  group_by(cue)%>%
  mutate(rt=as.numeric(rt))%>%
  summarize(mean_rt = mean(rt))%>%
  
```

# iat incongruent by novel word
```{r}
iat_incongruent = descriptive %>%
  filter(typeoftrial == "incongruent_iat", cue %in% c("dodish", "foobly", "geck", "mipp"))%>%
  group_by(cue)%>%
  mutate(rt=as.numeric(rt))%>%
  summarize(mean_rt = mean(rt))%>%
  filter(!ID %in% low_acc_IDs)
  
```
#GRAPHHH????
```{r}


# Combine datasets
combined_data <- bind_rows(
  mutate(iat_congruent_trials, trial_type = "Congruent"),
  mutate(iat_incongruent, trial_type = "Incongruent")
)

# Plot
ggplot(combined_data, aes(x = cue, y = mean_rt, fill = trial_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Mean Reaction Time for Congruent and Incongruent Trials by Familiar Novel Word",
       x = "Cue",
       y = "Mean Reaction Time",
       fill = "Trial Type") +
  theme_minimal()

```

```{r}
novel_con = descriptive %>%
  filter(typeoftrial == "congruent_iat", type_of_word %in% c("familiar novel", "unfamiliar novel"))%>%
  group_by(type_of_word)%>%
  mutate(rt=as.numeric(rt))%>%
  summarize(mean_rt = mean(rt))
```

# iat incongruent by novel word
```{r}
novel_incon = descriptive %>%
  filter(typeoftrial == "incongruent_iat", type_of_word %in% c("familiar novel", "unfamiliar novel"))%>%
  group_by(type_of_word)%>%
  mutate(rt=as.numeric(rt))%>%
  summarize(mean_rt = mean(rt))
```

# new graph 
```{r}

# Combine datasets
combined_data <- bind_rows(
  mutate(novel_con, trial_type = "Congruent"),
  mutate(novel_incon, trial_type = "Incongruent")
)

# Plot
ggplot(combined_data, aes(x = type_of_word, y = mean_rt, fill = trial_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Mean Reaction Time for Type of Novel Word",
       x = "Cue",
       y = "Mean Reaction Time",
       fill = "Trial Type") +
  theme_minimal()
```

# IAT RT inferential
```{r}
IATrt_model= lmer(rt ~ typeoftrial + (1 | ID),
                  data = subset_data)
summary(IATrt_model)
```

# Use in sentence inferential
```{r}
sentence_scoring = descriptive %>%
  filter(typeoftrial=="use_in_sentence") %>%
  mutate(AVERAGE_SENTENCE_SCORE = as.numeric(AVERAGE_SENTENCE_SCORE))

```

```{r}
sentence_model= lmer(AVERAGE_SENTENCE_SCORE ~ typeofword + (1 | ID),
                  data = sentence_scoring)
summary(sentence_model)
```

